#!/bin/bash

HOME_DIR=/opt/minecraft
DATA_DIR=${HOME_DIR}/data

mkdir -p /opt/minecraft/tmp
mkdir -p ${HOME_DIR}/minecraft
mkdir -p ${DATA_DIR}
cp /app/setup/minecraft_server.1.8.7.jar ${HOME_DIR}/minecraft/
echo "${HOME_DIR}" > ${HOME_DIR}/tmp/home
